// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyfmSKnIa-np195uN88wvZiKQfsHca_8',
    appId: '1:236408850937:web:697dbf2d4287b9faa61528',
    messagingSenderId: '236408850937',
    projectId: 'appfit-dd323',
    authDomain: 'appfit-dd323.firebaseapp.com',
    storageBucket: 'appfit-dd323.firebasestorage.app',
    measurementId: 'G-C802WK9ES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-BX8Ch28RH0yuBeeRQ3j9bQnLXHYE3c',
    appId: '1:236408850937:android:b8b5a9d2d147f942a61528',
    messagingSenderId: '236408850937',
    projectId: 'appfit-dd323',
    storageBucket: 'appfit-dd323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqesSWOGJyJXr3HaFB0wT3-rOpK1rA3L4',
    appId: '1:236408850937:ios:dbbb9821d1717387a61528',
    messagingSenderId: '236408850937',
    projectId: 'appfit-dd323',
    storageBucket: 'appfit-dd323.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqesSWOGJyJXr3HaFB0wT3-rOpK1rA3L4',
    appId: '1:236408850937:ios:dbbb9821d1717387a61528',
    messagingSenderId: '236408850937',
    projectId: 'appfit-dd323',
    storageBucket: 'appfit-dd323.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPyfmSKnIa-np195uN88wvZiKQfsHca_8',
    appId: '1:236408850937:web:45a0371e955d76dca61528',
    messagingSenderId: '236408850937',
    projectId: 'appfit-dd323',
    authDomain: 'appfit-dd323.firebaseapp.com',
    storageBucket: 'appfit-dd323.firebasestorage.app',
    measurementId: 'G-9SX25GVXY6',
  );
}
